CREATE DATABASE EMPLOYEES_PROYECT

USE EMPLOYEES_PROYECT

CREATE TABLE USERS(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
NAME VARCHAR(30),
SURNAME VARCHAR(30),
EMAIL VARCHAR(50),
PASS VARCHAR(20)
)

INSERT INTO USERS (NAME, SURNAME, EMAIL, PASS) 
VALUES ('JOHN', 'CONNOR', 'hastalavistababy@gmail.com', '1992')

SELECT * FROM USERS